In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Convertir a dataframe
df = pd.read_csv("GINEBRA.csv")
df

In [39]:
df

,Unnamed: 0,ID ANUNCIIO,ID SCRAPE,FUENTE INFO,NOMBRE ANFITRION,FECHA INICIO ANFITRION,TIEMPO DE RESPUESTA,TASA DE RESPUESTA,TASA DE ACEPTACION,SUPERANFITRION,CANTIDAD ANUNCIOS,CANTIDAD TOTAL ANUNCIOS,LATITUD,LONGITUD,TIPO DE PROPIEDAD,TIPO DE CUARTO,CAPACIDAD,BAÃ‘OS,DORMITORIOS,CAMAS,AMENIDADES,PRECIO,NOCHES MINIMAS,NOCHES MAXIMAS,MINIMO NOCHES MINIMAS,MAXIMO NOCHES MINIMAS,MINIMO NOCHES MAXIMAS,MAXIMO NOCHES MAXIMAS,PROMEDIO NOCHES MINIMAS,PROMEDIO NOCHES MAXIMAS,TIENE DISPONIBILIDAD,DISPONIBILIDAD 30D,DISPONIBILIDAD 60D,DISPONIBILIDAD 90D,DISPONIBILIDAD 365D,CANTIDAD REVIEWS,REVIEWS ULTIMOS 12M,REVIEWS ULTIMOS 30D,PUNTAJE RATING,PUNTAJE PRECISION,PUNTAJE LIMPIEZA,PUNTAJE CHECKIN,PUNTAJE COMUNICACION,PUNTAJE UBICACION,PUNTAJE VALOR,RESERVA INSTANTANEA,ANUNCIOS ANFITRION,ANUNCIOS HOGAR COMPLETO,ANUNCIOS HABITACION PRIVADA,ANUNCIOS HABITACION COMPARTIDA,REVIEWS POR MES
0,0,42515,20241229042300,city scrape,Noelle,2010-07-30,within a few hours,100.0,88%,f,1,1,46.201980,6.156720,Private room in rental unit,Private room,1,1.5,1.0,1.0,"[""Hair dryer"", ""Bathtub"", ""Stove"", ""Dishes and...",89.0,3,1125,3,3,1125,1125,3.0,1125.0,t,28,58,88,363,79,6,1,4.74,4.73,4.78,4.86,4.84,4.85,4.55,f,1,0,1,0,0.49
1,1,203997,20241229042300,city scrape,Mike,2011-08-21,within an hour,100.0,100%,t,6,12,46.199640,6.155800,Entire rental unit,Entire home/apt,2,1.0,1.0,0.0,"[""Hair dryer"", ""Lake access"", ""Private entranc...",130.0,5,730,5,5,1125,1125,5.0,1125.0,t,11,41,65,65,89,6,0,4.91,4.98,4.89,4.97,4.99,4.96,4.81,t,2,2,0,0,0.60
2,2,276025,20241229042300,city scrape,Gaby,2011-11-25,within an hour,100.0,100%,t,2,2,46.280310,6.168330,Entire rental unit,Entire home/apt,3,1.0,1.0,4.0,"[""Hair dryer"", ""Long term stays allowed"", ""Hot...",70.0,7,360,7,7,1125,1125,7.0,1125.0,t,2,2,2,156,122,4,1,4.64,4.70,4.74,4.88,4.89,4.77,4.68,f,1,1,0,0,0.78
3,3,338682,20241229042300,city scrape,Mike,2011-08-21,within an hour,100.0,100%,t,6,12,46.207080,6.155450,Entire rental unit,Entire home/apt,2,1.5,1.0,1.0,"[""Hair dryer"", ""Dishes and silverware"", ""Kitch...",133.0,5,365,3,5,1125,1125,5.0,1125.0,t,13,13,22,22,121,5,1,4.82,4.86,4.76,4.90,4.89,4.87,4.70,t,2,2,0,0,0.77
4,4,399388,20241229042300,city scrape,Oscar,2012-03-23,within an hour,100.0,89%,t,2,3,46.189040,6.139080,Private room in rental unit,Private room,2,1.0,1.0,1.0,"[""Hair dryer"", ""Long term stays allowed"", ""Hot...",53.0,2,1125,2,2,1125,1125,2.0,1125.0,t,4,4,27,269,57,7,1,4.85,4.81,4.88,4.95,4.89,4.70,4.70,f,2,0,2,0,0.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2752,2752,1318859808229991842,20241229042300,city scrape,Alexandre,2024-12-24,NaN,NaN,100%,f,1,2,46.199177,6.162477,Entire rental unit,Entire home/apt,4,1.0,2.0,1.0,"[""Microwave"", ""Free street parking"", ""Pets all...",125.0,3,730,3,3,730,730,3.0,730.0,t,28,58,88,363,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
2753,2753,1319353272672215826,20241229042300,city scrape,Jasmine,2019-06-18,NaN,NaN,50%,f,1,1,46.206610,6.138442,Entire rental unit,Entire home/apt,2,1.0,1.0,1.0,"[""Hair dryer"", ""Cleaning products"", ""Lake acce...",120.0,1,365,1,1,365,365,1.0,365.0,t,30,60,90,365,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
2754,2754,1319753554977771528,20241229042300,city scrape,Jennie,2024-09-05,within an hour,100.0,57%,f,2,3,46.198812,6.160810,Entire rental unit,Entire home/apt,2,1.0,1.0,1.0,"[""Kitchen"", ""Washer""]",109.0,1,365,1,1,365,365,1.0,365.0,t,29,59,89,364,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
2755,2755,1319753624300180036,20241229042300,city scrape,Jennie,2024-09-05,within an hour,100.0,57%,f,2,3,46.199807,6.161909,Entire rental unit,Entire home/apt,2,1.0,1.0,1.0,"[""Kitchen"", ""Washer"", ""Air conditioning""]",108.0,1,20,1,1,20,20,1.0,20.0,t,28,58,88,363,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
2756,2756,1320187730227740458,20241229042300,city scrape,Soufiane,2015-07-03,within an hour,100.0,NaN,f,1,2,46.214860,6.150470,Entire rental unit,Entire home/apt,4,1.0,1.0,2.0,"[""Conditioner"", ""Hot water kettle"", ""Bathtub"",...",160.0,2,15,2,3,15,15,2.0,15.0,NaN,7,7,7,7,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [3]:
# Ajustar maximo de filas para visualizar todo

pd.options.display.max_rows = 100

In [4]:
pd.options.display.max_columns = None

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2757 entries, 0 to 2756
Data columns (total 51 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      2757 non-null   int64
 1   ID ANUNCIIO                     2757 non-null   int64
 2   ID SCRAPE                       2757 non-null   int64
 3   FUENTE INFO                     2757 non-null   object
 4   NOMBRE ANFITRION                2757 non-null   object
 5   FECHA INICIO ANFITRION          2757 non-null   object
 6   TIEMPO DE RESPUESTA             2015 non-null   object
 7   TASA DE RESPUESTA               2015 non-null   float64
 8   TASA DE ACEPTACION              2309 non-null   object
 9   SUPERANFITRION                  2726 non-null   object
 10  CANTIDAD ANUNCIOS               2757 non-null   int64
 11  CANTIDAD TOTAL ANUNCIOS         2757 non-null   int64
 12  LATITUD                         2757 non-null   float64
 13  LONGITUD                        2757 non-null   float64
 14  TIPO DE PROPIEDAD               2757 non-null   object
 15  TIPO DE CUARTO                  2757 non-null   object
 16  CAPACIDAD                       2757 non-null   int64
 17  BAÃ‘OS                           2067 non-null   float64
 18  DORMITORIOS                     2550 non-null   float64
 19  CAMAS                           2063 non-null   float64
 20  AMENIDADES                      2757 non-null   object
 21  PRECIO                          2068 non-null   float64
 22  NOCHES MINIMAS                  2757 non-null   int64
 23  NOCHES MAXIMAS                  2757 non-null   int64
 24  MINIMO NOCHES MINIMAS           2757 non-null   int64
 25  MAXIMO NOCHES MINIMAS           2757 non-null   int64
 26  MINIMO NOCHES MAXIMAS           2757 non-null   int64
 27  MAXIMO NOCHES MAXIMAS           2757 non-null   int64
 28  PROMEDIO NOCHES MINIMAS         2757 non-null   float64
 29  PROMEDIO NOCHES MAXIMAS         2757 non-null   float64
 30  TIENE DISPONIBILIDAD            2683 non-null   object
 31  DISPONIBILIDAD 30D              2757 non-null   int64
 32  DISPONIBILIDAD 60D              2757 non-null   int64
 33  DISPONIBILIDAD 90D              2757 non-null   int64
 34  DISPONIBILIDAD 365D             2757 non-null   int64
 35  CANTIDAD REVIEWS                2757 non-null   int64
 36  REVIEWS ULTIMOS 12M             2757 non-null   int64
 37  REVIEWS ULTIMOS 30D             2757 non-null   int64
 38  PUNTAJE RATING                  2081 non-null   float64
 39  PUNTAJE PRECISION               2081 non-null   float64
 40  PUNTAJE LIMPIEZA                2081 non-null   float64
 41  PUNTAJE CHECKIN                 2081 non-null   float64
 42  PUNTAJE COMUNICACION            2081 non-null   float64
 43  PUNTAJE UBICACION               2081 non-null   float64
 44  PUNTAJE VALOR                   2081 non-null   float64
 45  RESERVA INSTANTANEA             2757 non-null   object
 46  ANUNCIOS ANFITRION              2757 non-null   int64
 47  ANUNCIOS HOGAR COMPLETO         2757 non-null   int64
 48  ANUNCIOS HABITACION PRIVADA     2757 non-null   int64
 49  ANUNCIOS HABITACION COMPARTIDA  2757 non-null   int64
 50  REVIEWS POR MES                 2081 non-null   float64
dtypes: float64(17), int64(23), object(11)
memory usage: 1.1+ MB

Filtro a: Los registros de los host cuyo host response rate sea mayor a 95% y que no sean superhost

In [ ]:
#Eliminar un signo de una columna

df["TASA DE RESPUESTA"]=df["TASA DE RESPUESTA"].str.replace('%', '')

In [20]:
#ConversiÃ³n de tipo de dato de columna

df["TASA DE RESPUESTA"]=df["TASA DE RESPUESTA"].astype(float)

In [41]:
#Filtro a

filtro_a = df[(df["TASA DE RESPUESTA"] >= 95) & (df["SUPERANFITRION"] == "f")]

In [42]:
#Convertir archivo filtrado a CSV

filtro_a.to_csv("filtro_a.csv")

Filtro b: Los registros cuyas propiedades no tengan 1 baÃ±o

In [43]:
#Filtro b

filtro_b = df[df["BAÃ‘OS"] != 1]

In [44]:
#Convertir archivo filtrado a CSV

filtro_b.to_csv("filtro_b.csv")

Filtro c: Los registros que tengan un precio entre $100 y $200

In [30]:
#Eliminar un signo de una columna

df["PRECIO"]=df["PRECIO"].str.replace('$', '')
df["PRECIO"]=df["PRECIO"].str.replace(',', '')

In [31]:
#ConversiÃ³n de tipo de dato de columna

df["PRECIO"]=df["PRECIO"].astype(float)

In [45]:
#Filtro c

filtro_c = df[(df["PRECIO"] >= 100) & (df["PRECIO"] <= 200)]

In [46]:
#Convertir archivo filtrado a CSV

filtro_c.to_csv("filtro_c.csv")

Filtro d: Los registros que sean instant bookable y que sean superhost

In [47]:
#Filtro d

filtro_d = df[(df["RESERVA INSTANTANEA"] == "t") & (df["SUPERANFITRION"] == "t")]

In [48]:
#Convertir archivo filtrado a CSV

filtro_d.to_csv("filtro_d.csv")

Filtro e: Los registros de los tipos de cuarto: Hotel room o Private room

In [49]:
#Filtro e

filtro_e = df[(df["TIPO DE CUARTO"] == "Private room") | (df["TIPO DE CUARTO"] == "Hotel room")]

In [50]:
#Convertir archivo filtrado a CSV

filtro_e.to_csv("filtro_e.csv")

Filtro f: Los registros que tengan mÃ¡s de 4 accommodates

In [51]:
#Filtro f

filtro_f = df[df["CAPACIDAD"] > 4]

In [52]:
#Convertir archivo filtrado a CSV

filtro_f.to_csv("filtro_f.csv")